### PR TITLE
naming convention and light theme fix

### PR DESCRIPTION
**Pull request by anthonybaldwin**
Changed naming convention to use 'Show' and 'Hide' to more closely resemble the other toggle buttons. Additionally, I added the color vars Discord is using on the buttons instead of hex so this works for dark and light theme. I bumped the minor by 1?

### CODE REVIEW

**Comment by anthonybaldwin** [comment]
For reference, before:
image
image
image / image
image
image
image

And after:
image
image
image / image


image
image
image

**Comment by anthonybaldwin** [comment]
Changed to 'Show Game' and 'Hide Game' instead. Personal preference.

image
image

**Comment by anthonybaldwin** [comment]
Meh, not using this actually, and some of the changes are personal preference. You can use `colorColor` in place of `var(--interactive-normal)` to take care of the hover state (instead of ` onButtonMouseOver({ target }) {`, and would only need 2 SVGs (instead of 4).

Like here: https://github.com/Juby210/game-activity-toggle/pull/1

Thank you for your plugin. :)

**Comment by greymesa** [comment]
this is cool though

**Pull request closed without merging**
